default: &default
  adapter: postgresql
  encoding: unicode
  database: development-covid
  pool: 5
  username:
  password:
  timeout: 5000

development:
  <<: *default
  database: development-covid-v1

test:
  <<: *default
  database: test-covid-v1

production:
  <<: *default
  database: production-covid-v1